import {
    Users,
    Search,
    Mail,
    ArrowRight,
    ArrowUpRight,
    Building2,
    BarChart3,
    UserCheck,
    Clock,
    MessageSquare,
    User,
    Briefcase,
    FileText,
    Award,
    BookOpen,
    Link,
    MapPin,
    Trophy,
    Settings,
    Upload,
} from "lucide-react";

// ✅ Define a mapping of string names to actual React components
export const iconMap: Record<string, React.ElementType> = {
    Users,
    UserCheck,
    Search,
    Mail,
    ArrowRight,
    ArrowUpRight,
    Building2,
    BarChart3,
    Clock,
    MessageSquare,
    User,
    Briefcase,
    FileText,
    Award,
    BookOpen,
    Link,
    MapPin,
    Trophy,
    Settings,
    Upload
};